### ISSUE TITLE
UserStatus IllegalArgumentException

### ISSUE THREAD

**Issue by jt15** [nightowlengineer/groupsio-api-java#7]
java.lang.IllegalArgumentException: Cannot deserialize value of type `engineer.nightowl.groupsio.api.domain.UserStatus` from String "user_status_not_confirmed": value not one of declared Enum instance names: [user_status_bounced, user_status_inactive, user_status_notconfirmed, user_status_bouncing, user_status_confirmed]
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: java.lang.Object[][11]->engineer.nightowl.groupsio.api.domain.Subscription["user_status"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3750)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3668)
	at engineer.nightowl.groupsio.api.resource.MemberResource.getMembersInGroup(MemberResource.java:86)

**Comment by nightowlengineer** [comment]
Thanks - looks like a typo in that enum. If you want to put a PR in I'd be happy to merge and publish, otherwise I'll get onto it in the next couple of weeks.

**Comment by nightowlengineer** [comment]
Should be sorted now with version 0.0.3 (may take a while to sync around the repos).

**Comment by jt15** [comment]
Thanks for fixing it.
